version: "3.7"

services:
  naming-server:
    image: in28min/mmv2-naming-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports: 
      - "8000:8000"
    networks:
      - currency-network
networks:
  currency-network:
