version: "2"

services:
  proxy:
    build:
      context:
      dockerfile: nginx.Dockerfile
    image:
      ports:
        - : "80:80"
  web:
    image: httpd
    volumes:
      - /html:usr/lib/var/index.html
